services:
  mongodb:
    image: mongo:latest
    container_name: civicvoice-db
    ports:
      - "27017"
    volumes:
      - mongodb_data:/data/db
    restart: always

  api:
    build: 
      context: ../civicvoice_api
    container_name: civicvoice-api
    ports:
      - "3005:3005"
    depends_on:
      - mongodb
    environment:
      - PORT=3005
      - DB_URI=mongodb://mongodb:27017/civicvoice
      - JWT_SECRET=prod_secret_mali_2026
      - JWT_REFRESH_SECRET=prod_refresh_mali_2026
      - CORS_ORIGIN=https://civicvoices.touredri.dev
      - NODE_ENV=production
    restart: always

  frontend:
    build:
      context: ../civicvoice_backoffice
      args:
        - VITE_API_URL=https://civicvoice.touredri.dev/api
    container_name: civicvoice-frontend
    ports:
      - "3000:80"
    depends_on:
      - api
    restart: always

volumes:
  mongodb_data: